In [1]:
import numpy as np


In [2]:
arr = np.linspace(0,1,12)
print(arr)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [3]:
reshaped_arr = arr.reshape(3,4)
print(reshaped_arr)

[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


In [6]:
matrice_casuale = np.random.rand(3,4)
print(matrice_casuale)

[[0.9004207  0.39170763 0.48905692 0.67610534]
 [0.07593007 0.28916444 0.96075775 0.1503843 ]
 [0.59378193 0.49937918 0.7014608  0.20222859]]


In [7]:
somma_matrice = np.sum(reshaped_arr)
somma_matrice_casuale = np.sum(matrice_casuale)

print("Somma degli elementi della matrice 3x4: ", somma_matrice)
print("Somma degli elemnti matrice casuale: ", somma_matrice_casuale)

Somma degli elementi della matrice 3x4:  6.0
Somma degli elemnti matrice casuale:  5.930377648045896
